variables:
  GOFLAGS: -mod=vendor

default:
  image: "quay.ubisoft.com/uks/golang:1.16.2"
  tags: [uks-private]

before_script:
  - export TAG=$(git describe --abbrev=0)

stages:
  - build
  - release

build:
  stage: build
  script:
    - go test ./...
    - GOOS=linux go build -a -tags netgo -trimpath -ldflags "-s -w -X main.version=$TAG" -o haproxy-parser-linux
    - GOOS=darwin go build -a -tags netgo -trimpath -ldflags "-s -w -X main.version=$TAG" -o haproxy-parser-darwin
  artifacts:
    paths:
      - haproxy-parser-linux
      - haproxy-parser-darwin
    expire_in: 1h

release:
  image: quay.ubisoft.com/patrickdappollonio/artifactorize
  stage: release
  script:
    - artifactorize haproxy-parser-linux generic/uks/pdappollonio/haproxy-parser/haproxy-parser-linux_$CI_BUILD_TAG
    - artifactorize haproxy-parser-darwin generic/uks/pdappollonio/haproxy-parser/haproxy-parser-darwin_$CI_BUILD_TAG
  only:
    - tags

